name: Test Windows support

on: [push, pull_request]

jobs:
  windows-test:
    runs-on: windows-latest

    strategy:
      matrix:
        python:
          - 3.9
          - 3.8
          - 3.7

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}

    - name: Install dependencies
      shell: bash
      run: pip install pywin32

    - name: Build Windows driver
      shell: bash
      run: python3 setup.py build_ext -i

    - name: Upload Windows driver
      uses: actions/upload-artifact@v2
      with:
        name: drivers_win7_x64
        path: drivers/win7/x64

    - name: Install chipsec
      shell: bash
      run: python3 setup.py install

    - name: Run chipsec_main
      shell: bash
      run: chipsec_main
