name: Test Linux support

on: [push, pull_request]

jobs:
  ubuntu-py3-test:
    strategy:
      matrix:
        ubuntu-version:
          - ubuntu-20.04
          - ubuntu-18.04
          - ubuntu-16.04
    runs-on: ${{ matrix.ubuntu-version }}

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update -q
        sudo apt-get install -qqy python3-setuptools nasm

    - name: Build the driver
      run: python3 setup.py build_ext -i

    - name: Install chipsec
      run: sudo python3 setup.py install

    - name: Run chipsec_main
      run: sudo chipsec_main

  ubuntu-py2-test:
    strategy:
      matrix:
        ubuntu-version:
          - ubuntu-20.04
          - ubuntu-18.04
          - ubuntu-16.04
    runs-on: ${{ matrix.ubuntu-version }}

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update -q
        sudo apt-get install -qqy python-setuptools nasm

    - name: Build the driver
      run: python2 setup.py build_ext -i

    - name: Install chipsec
      run: sudo python2 setup.py install

    - name: Run chipsec_main
      run: sudo chipsec_main
